### PR TITLE
Mod: Various pilots in alternative ships

### PR DESCRIPTION
**Pull request by rune-b**
Inspired by this reddit post:
https://www.reddit.com/r/XWingTMG/comments/cgjvjd/what_would_you_price_a_vader_tie_defender/

### CODE REVIEW

**Comment by rune-b** [comment]
Added 10 more alternative pilots. Complete list:

Vader in Defender
Maarek Stele in Star Wing
Corran Horn (with and without Force), Hera Syndulla and Tycho Celchu as X-Wing pilots
Ezra Bridger, Hera Syndulla and Sabine Wren as A-Wing pilots
Hera Syndulla as B-Wing pilot
Hera Syndulla as U-Wing pilot


Imgur album with all the pilot cards:
https://imgur.com/a/mp6KsUm

**Comment by rune-b** [comment]
Hopefully the point costs I made up are not too bad...

**Comment by SovietToaster14** [comment]
There's a small typo on the Vader Defender card twice. Says "preform" should be perform.

**Comment by rune-b** [comment]
Well spotted. However, I didn't make the cards, and since it has no effect on gameplay I think I will leave it for now

**Pull request merged**
