### PR TITLE
Electronic Baffle & Rage Upgrades

### PR DESCRIPTION
**Pull request by jamorbal**
Hello Guys,

I've done with Electronic Baffle and Rage upgrades.
I've tested them along Pattern Analyzer for checking out its full performance.

### CODE REVIEW

**Comment by Sandrem** [comment]
About "Rage" upgrade.
You use old template, where AttachToShip is used. Please, change code to use GenericAbility and UpgradeAbilities.Add(<ability class>)

Code of Electronic Baffle is OK

**Comment by jamorbal** [comment]
Hello,

How I could attach the action? I tried with the new Template, but I didn’t see how to do it.

Regards

**Comment by Sandrem** [comment]
See Astromech/R2-F2 as example.

Just move code from AttachToShip to ActivateAbility

**Comment by jamorbal** [comment]
mmm ok! I’ll take a look into.

Thanks a lot!!  I’m having so much fun doing such things XD.

Regards!! ^^

**Comment by jamorbal** [comment]
Both upgrades has been modified.
Rage uses the new Template.
Electronic Baffle controls when the host ship is destroyed by the use of the electonic baffle, it's crazy to do it, but it could happen

**Comment by Sandrem** [comment]
Good work!

**Pull request merged**
