### PR TITLE
Moved Zeta Leaders ability to attack from start of combat.

### PR DESCRIPTION
**Pull request by Conzar**
I moved zeta leader to use OnAttackStartAsAttacker.

### CODE REVIEW

**Comment by Sandrem** [comment]
OnAttackStartAsAttacker is correct place for activation of ability.

But after testing I decided to revert this pull request.
Please, make additional changes:
1) Use quotes in name of pilot (as on card)
2) Text of ability says "roll additional dice", not "increase your attack value by 1". This can cause problems later. For example how to roll additional dice - see ability of Fenn Rau (Scum). Change ability is this way, please.

**Comment by Conzar** [comment]
`Use quotes in name of pilot (as on card)`
If I use the quotes, than the pilot template texture doesn't work.  I guess that is a potential bug w/ the way textures are auto-loaded?

**Comment by Sandrem** [comment]
Maybe, I will fix this bug after your pull request.

**Comment by Sandrem** [comment]
I see!
in "Assets\Resources\ShipStandInsert\TIE FO Fighter\"
rename "Zeta_Leader.jpg" to "_Zeta_Leader_.jpg"

**Comment by Sandrem** [comment]
Oh, Github's markup changes name to italics. Just use underscore at the begining and the end of name, like in Omega Leader texture name.

**Pull request merged**
