### PR TITLE
Update TargetLockAction.cs

### PR DESCRIPTION
**Pull request by DejaFu**
AI will now use the Target Lock Action if they have munitions with charges available, or if they have 2 or more Force tokens.

AI will spend target lock tokens on targets when their attack dice can't be resolved otherwise.

### CODE REVIEW

**Comment by Sandrem** [comment]
Please, avoid use of names of ships/pilots/upgrades in general code.
I changed mention of E-wing to ship's TargetLockMinRange

**Comment by DejaFu** [comment]
I looked at the target lock code, and it looks like the Jedi only have a
priority of 15 for target locking if they have 2 or more Force.  When I was
playing as Jedi, I found it was better for me to use Target Lock than focus
if I had a good amount of Force, as I could use the Force to make up for
the lack of focus.  The test for that value being set at all also checks if
the result is 0 before checking for how much Force they have.  Should that
value be += 55 instead of +=15 or was there another reason to change it?
 - Donner

**Comment by Sandrem** [comment]
@DejaFu I didn't change this value, it was 15 in original pull request. You can modify it, if you think that this value should be updated.

**Comment by DejaFu** [comment]
Oh!  Well then...  I’ll get on that.  Thanks!
 - Donner

**Pull request merged**
