### PR TITLE
Tactician

### PR DESCRIPTION
**Pull request by rune-b**

### CODE REVIEW

**Comment by Sandrem** [comment]
ShipDistanceInformation is used to measure distance between ship for abilities, without arc restrictions.
If you want to measure distance in arc - use Range of ShipShotDistanceInformation

**Comment by Sandrem** [comment]
Also, you can use pre-calculated Combat.ShotInfo instead of re-checking.

**Comment by Sandrem** [comment]
Range must be == 2

**Comment by rune-b** [comment]
Done

**Pull request merged**
