### PR TITLE
Dedicated talent

### PR DESCRIPTION
**Pull request by bitsai**
Work-in-progress implementation of the Republic's Dedicated faction talent.  Have implemented and tested the bulk of the functionality, except for the following:

- line 18: the talent should be restricted to non-limited (aka generic) ships only.  what is the best way to implement that?

- line 35: because a single defender may be within range of multiple Dedicated friendlies, I would like to have the modification name be something like "Dedicated: Squad Seven Veteran N", where N is the number assigned to the ship in the game (the one that shows up when the user presses Alt/Option).  How do I get access to that number?

- line 69: I have a general idea of how I want to set the AI priority: if the number of attacker hit/crit results > number of defender evade results, then AI should use the ability, otherwise don't.  but I don't know what the proper range of integer values is for AI priority.  should it be 0 for not using the ability?  and what should it be when the AI should use it?

### CODE REVIEW

**Comment by Sandrem** [comment]
1) See AngledDeflectors for StatValueRestriction. I propose you to add support of Limited value check too.
As alternative, you can create own simple new class, like NonLimitedRestriction.

2) ID of ship is "ship.ShipId"
I propose you to show name of dice modification shorter, like "Dedicated (ID:3)"

3) See GenericAction.cs for examples of priority of dice modifications.
0 - dice modification is not used at all
As I see order of dice modification, this is somewhere lower than 90 (free reroll) and near 80 (reroll that costs you target lock token).
I propose following AI: if ship has lock of defender, compare what is better - TL (for example, when 2 blanks, or 2 not-hits without focus/force) or Dedicated (when only 1 blank). And set priority 79 for first case and 81 for second case.
And, maybe, if chances to hit are very low - don't use it at all (priority 0). For example, you can calculate average green dice results by number and focus/force presence.
(There are no methods/classes to calculate these chances, you can do this manually - See FE Han Solo pilot of example of calculations)

**Comment by bitsai** [comment]
@Sandrem thank you for the speedy feedback!

w.r.t. AI priority: minor clarification, Dedicated is a **defensive** ability.  looking at defensive priorities in GenericAction.cs, I think Dedicated falls somewhere between `Free rerolls limited by side` (95) and `Free change limited by side if 1` (100), since functionally it seems like a `Free rerolls limited by side if 1`.  What do you think of this logic?

```
if # of attacker hit/crit results > # of defender evade results AND # of defender blank result > 0, AI priority = 98
else AI priority = 0
```

w.r.t. dice modification name: I tested setting the name to `HostName + "(ID: " + HostShip.ShipId + ")"`, but in my test game, the name showed up as `Dedicated(ID: 1)` even though the effect was coming from the last ship in my list, which showed ID 4 when I pressed the Alt/Option key.  See screenshot below (sorry, I wasn't able to take a screenshot with ship ID's displayed):

Screen Shot 2019-07-02 at 8 37 39 AM

**Comment by Sandrem** [comment]
2) No idea why ship.ShipId doesn't work correctly. Please, commit your change in name of dice modification, I will test and debug.

3) Oh, sorry.
This dice modification requires you to assign debuff token, so I treat it as "not-free reroll (85)". (Serissu is an example of free defense dice reroll with priority 90 - your dice modification is worse, so priority must be lower,) As it is limited by side, it should have higher priority. So, I propose priority 87 (you can add this value to list of default values in GenericAction.cs, as "not-free rerolls limited by side if 1").
Logic seems to be OK.

**Comment by bitsai** [comment]
Thanks!  I'll have this finalized later today.

**Comment by bitsai** [comment]
@Sandrem ok, I think that covers everything that's been discussed.  Let me know what you think!

**Comment by Sandrem** [comment]
I dound reason of problem with ShipID - they were assigned to ships only on step "Create model for board", before "Initialize abilities", so all ships had ID:1 during that step.
I fixed this issue.
All another code seems to be OK.

**Pull request merged**
