### PR TITLE
Captain Kagi and Colonel Jendon

### PR DESCRIPTION
**Pull request by rune-b**

### CODE REVIEW

**Comment by Sandrem** [comment]
>> If an enemy ship equipped with Fire-Control System is at range to acquire a target lock on Captain Kagi and attacks a ship other than Captain Kagi, the target lock provided by Fire-Control System must be acquired on the defender, not Captain Kagi

I propose don't include this code in 0.2.0, but first implement Fire-Control System and make sure that this rule is supported too.

**Comment by rune-b** [comment]
OK

**Comment by rune-b** [comment]
I'll do Fire-Control System too, unless you've started on it already

**Comment by Sandrem** [comment]
Not started

**Comment by rune-b** [comment]
Now all Lambda pilots and Fire-Control System are included. 

I will take Weapons Engineer next if that's ok, since it has some interactions with these cards.

**Comment by Sandrem** [comment]
Yes, Weapons Engineer was not included in Wave 2 content because there are a lot of TL interations are needed.
Also, Manaroo needs ReassignTargetLock for her ability.

**Comment by rune-b** [comment]
Closing this PR. Will make a new one with pilots updated to the new ability system

**Pull request closed without merging**
