### PR TITLE
Restricted upgrades

### PR DESCRIPTION
**Pull request by rune-b**
Added some upgrades that are only allowed for certain ships:

- Chardaan Refit
- Twin Ion Engine Mk II
- Moldy Crow

Vectored Thrusters' size restriction needs to be fixed when base sizes are implemented (I saw that you are working on that on another branch)

### CODE REVIEW

**Comment by Sandrem** [comment]
Great work!
I plan to finish Large Ships support this week, I will inform you.

**Comment by Sandrem** [comment]
In "Large Ships" branch I don't see "Twin Ion Engine Mk II" in list of modification for all TIEs. (I didn't test in "development" so far). Maybe, something was broken. You can ignore this, I will check later.
Other upgrades work fine.

**Comment by rune-b** [comment]
I had that same problem for Moldy Crow initially when I had enabled the Title slot for all ships. But I moved it to HWK only, since not all ships have title cards even if they technically has the slot, and the the problem vanished

I suspect it has something to do with it not being available when the dropdown is first initialized for the A-Wing (since that is default selected ship for rebels). Is the default Empire ship in the Large Ships branch a non-TIE ship perhaps?

I debugged the Moldy Crow problem but could not find anything wrong in the C# code, so perhaps it is Unity-related (which I don't know how to debug)

**Comment by Sandrem** [comment]
Yes, current initial ship for Empire in this branch is "Firespray-31'.

When Large Ships will be done - I plan to change work of upgrade bar and upgrade slots (use classes in both cases) to allow titles of TIE Advanced, TIE Bomber and Kihraxz.

I propose to left current problem as is - I will fix it during refactoring. Or you can do this instead - if you understand my code in this part.

**Comment by rune-b** [comment]
I debugged into the AddUpgradeLine() method in RosterBuilder, and the Moldy Crow title was present in the upgradeList in this statement:
newUpgradeLine.transform.GetComponent<Dropdown>().AddOptions(upgradeList);

Why it did not show up in the dropdown I don't know, but the AddOptions method is a part of Unity so I could not debug it further

**Pull request merged**
