### PR TITLE
WIP Tractor Beam PR For Initial Review

### PR DESCRIPTION
**Pull request by ajmath**
Here is the first pass at tractor beam support.  Please let me know if these changes work for you.  I ended up having to make a lot of broad changes related to the number of bindings to`Selection.ThisShip`.  There will likely need to be more once I start testing network games.  I'm also not sure about using the BarrelRoll and Boost sub-planning phases without their selection phases, it seems like it might be too tightly coupled but that might be okay.

What works:
* Boosting/Barrel rolling enemy ships
* Boosting/Barrel rolling friendly ships
* Agility adjustments
* Damage for boosting/barrel rolling onto a rock
* Space tug toot toot
* Network play
* Shadow Caster title

What doesn't work:
* Picking an BR that overlaps another ship and then getting to pick another option
* Trigger the tractor beam planning phase after assigning the token from Ketsu's pilot ability
* Multiple ships with Unkar Plutt
* Single ships with Unkar Plutt
* The ship base inserts for Unkar Plutt are missing so I added a crappy photoshop version

What hasn't been tested (and probably doesn't work):
* Interactions with other cards like Intensity and Black One
* Damage for boosting/barrel rolling onto a rock when only the template overlaps

### CODE REVIEW

**Comment by Sandrem** [comment]
TractorBeamRule.cs:
CheckForTractorBeam - there are can be few effects that can be activated after token is assigned (for example, "When you assigned ANY token - you MAY lose 1 hp to discard it" - will start decision subphase). To avoid start of two effects/subphases in parallel way, triggers must be used. If triggers are used, then player will see window "select order of triggers" and effects will be resolved one by one.
So, CheckForTractorBeam  must instead register trigger. And PerformTractorBeamEffect must be called as trigger's effect.

**Comment by Sandrem** [comment]
TractorBeam.cs
1) RegisterTractorBeamEffect() - you can use RegisterAbilityTrigger method, this is more simple call of RegisterTrigger for abilities.
2) Seems that you don't need to resolve "Triggers.ResolveTriggers(TriggerTypes.OnAttackHit, ...)"  manually - it will be resolved by Triggers code in normal way. Try to use only "AssignToken(token, Triggers.FinishTrigger)".

TractorBeamToken.cs
"CanBeUsed = false;" is used for "Carnor Jax"-like effects. There is no need to set this flag if token doesn't grant own Action.

SpaceTugTractorArray.cs
1) You can skip "isLimited = false;" - it is false by default.
2) You use older template (uses AttachToShip) - use modern template with GenericAbility and UpgradeAbilities.Add...
3) Seems that you don't need to resolve "Triggers.ResolveTriggers(TriggerTypes.OnAttackHit, ...)"  manually - it will be resolved by Triggers code in normal way. Try to use only "AssignToken(token, Triggers.FinishTrigger)".

ShadowCaster.cs
1) If you inside combat between two ships, you can use pre-measured Combat.ShotInfo (calculations of ShipShotDistanceInformation are heavy, so it should be avoided if pre-measured is already present)
2) CheckShadowCasterAbility - there are can be few effects that can be activated after token is assigned (for example, "When you assigned ANY token - you MAY lose 1 hp to distcard it" - will start decision subphase). Game needs to wait until decision subphase is finished. So if you assign a token - it must be done inside a trigger, and trigger must be finished in AssignToken.
You need to register trigger inside CheckShadowCasterAbility, then call AssignToken(token, Triggers.FinishTrigger) inside trigger's effect.

**Comment by Sandrem** [comment]
Network games sync decision selection and end of boost/barrel roll - so seems that no network-specific changes are required.

You're doing a great job, I like your code! =)

**Comment by ajmath** [comment]
Thanks for the feedback.  I updated with your changes.  I ended up removing the ship param for the boost/br methods in GameMode since they don't seem to be needed/used.

Do you have any suggestions for the things listed in "What doesn't work" above?

**Comment by Sandrem** [comment]
> suggestions for the things listed in "What doesn't work"

I will check your code locally tomorrow.

**Comment by ajmath** [comment]
Thanks! I suspect it’s something to do with the triggering of the direction
selection and boost/br subphases.

**Comment by Sandrem** [comment]
Spacetug Tractor Array:
When you selected a ship and see "Select direction" window, ship-info panels are still pulsing with "Select me effect".
You can fix this by calling "SelectShipSubPhase.FinishSelectionNoCallback();" immediate after ship was selected. (This wll finish "Select Ship" subphase, but will not call "Triggers.FinishTrigger").

**Comment by Sandrem** [comment]
If you try to perform boost off the board - then it fails and calls "BoostPlanningSubPhase.CancelBoost();". It calls "PreviousSubPhase.Resume();".
Try to debug this part. Correct behavior - you need to return to previous suphase (Select direction of Tractor Beam token effect) and call it's "Resume" method, where window "Select direction" is shown.

If you still will have problems in this part of code - inform me again, I will take a closer look.

**Comment by Sandrem** [comment]
Ketsu Onyo:
When you selected a ship for ability, you need to assign tractor beam to targer, and as a callback - call finish of "Select Ship" subphase (SelectShipSubPhase.FinishSelection). This method calls Triggers.FinishTrigger as part of it's code.
So you:
1) Don't need to call Triggers.ResolveTriggers - is will be resolved as part of AssignToken call.
2) Don't need to call Triggers.FinishTrigger - it is already called as part of FinishSelection. As result, you call "FinishTrigger" twice.

**Comment by Sandrem** [comment]
Also for Ketsu:
You need to call "SelectShipSubPhase.FinishSelectionNoCallback" when ship is selected, before token is assigned and "Select Direction" subphase is started.
Otherwise you have one more subphase in list of subphases to finish - and game stays in "Combat Start", because "Select Ship" is finished instead of "Combat Start".

**Comment by Sandrem** [comment]
Unkar Plutt:
1) Game crashes because "Selection.ThisShip" must be used for PlaySound of movement and asteroid collisions check. I think that it is safe to set "Selection.ThisShip" as ship that will be assigned token,
2) I see that you try to use recursion, but I propose another way to handle few triggers.
Just use "foreach bumped ship - register trigger" in RegisterPilotAbility. You will have few triggers active, player will see "Select order of triggers" window and can select order to assign tokens/move.

**Comment by Sandrem** [comment]
unkar_plutt

**Comment by ajmath** [comment]
I pushed up some minor fixes but there are still these issues:
* Space Tug is moving to the next ship in activation order after selection and before tractor beam is resolved
* Ketsu and Unkar's ability work by themselves but do not stack together (though Unkar's are working with multiple ships) as they are skipping to the next phase before the other's ability can be triggered

The core problem I think I'm seeing now is that the callback for AssignToken is triggering long before the tractor beam process is done.  I was thinking of adding a callback to the token itself but it seems there is a better way to do this with all of the other code you've setup.

**Comment by ajmath** [comment]
I believe I've worked out the issue with space tug causing the next ship to proceed with activation.

Still have these two issues:
* Triggering multiple tractor beam effects at the same time results in only the first one being triggered.  For example, if there are multiple ships touching Unkar only one will get a token.  Similarly, if Ketsu and Unkar both trigger, only one ship will get a tractor beam and the other triggers will be finished
* If you select an invalid position for a tractor beam BR, there is no redos.

I did verify Ketsu/Unkar interactions with other Start of Combat triggers (Manaroo) and that works great.

@Sandrem Any idea what's going on with the canceling triggers?

**Comment by ajmath** [comment]
Thanks for the merge.  FYI, there is still the outstanding issue of multiple tractor beam effects not resolving appropriately.  Also, you might want to consider doing a sqaush merge on PRs like this in the future where I've added a bunch of garbage commit messages ;).  It will make it look like one big commit for the whole PR.  You can do a squash by clicking the drop-down on the merge button.

**Comment by Sandrem** [comment]
Thank you for information =)

**Pull request merged**
