### PR TITLE
Added Lightweight Frame/Emperor Palpatine/Other bug fixes

### PR DESCRIPTION
**Pull request by Jimmy5910**
I wasn't sure about the meta file, but all the code should be there for Lightweight Frame to work properly.

### CODE REVIEW

**Comment by Jimmy5910** [comment]
Improved AI for Accuracy Correcter as well.

**Comment by Jimmy5910** [comment]
Standby. Found some issues. Will update soon.

**Comment by Sandrem** [comment]
Hello. We have Slack workspace for developers, you are welcome:
<link is removed>
If you have any problems - contact me there, I can give you examples of code and advices.

**Comment by Jimmy5910** [comment]
Okay, I think should be working properly now.

**Comment by Jimmy5910** [comment]
Bug fix for #708

**Comment by Jimmy5910** [comment]
Bug fix for #716

**Pull request merged**
