### PR TITLE
Allow AI to use Full Throttle ability

### LINKED ISSUE #1903: Tie Defender AI and Full Throttle Ability
When a Tie Defender controlled by AI successfully completes a 3-5 speed maneuver, it doesn't do the free evade action from Full Throttle. It used to, but for some reason doesn't anymore

### PR DESCRIPTION
**Pull request by bitsai**
Fixes #1903

### CODE REVIEW

**Comment by Sandrem** [comment]
Strange. AI should see decision UI and click "DefaultDecisionName = Yes" button.
Please, try to debug why AI doesn't do this.

**Comment by bitsai** [comment]
@Sandrem the AI does click "YES" on the initial decision UI.  the problem was that this calls `PerformFreeEvadeAction`, which calls `AskPerformFreeAction` (with `isForced: true`) to create yet another decision phase.  for human players, the Evade action is taken instead of showing another decision UI bc of the `isForced: true` flag.  but here AI will try to pick an action based on priority, and the Evade action has priority 0 except under very specific circumstances.

I've updated the PR so that if `isForced: true` is set, AI will take the first action (just like the code for human players).

I checked other abilities that call `AskPerformFreeAction` with `isForced: true`; only Paige Tico's ability will lead to the AI taking an action this way.  I played a test game against a Resistance StarFortress w/ Paige Tico gunner and verified that there were no crashes.

**Comment by bitsai** [comment]
P.S. the other option I tested (you can see it in the commit history) was increasing the Evade action's priority if it's a free action.  but IMHO it's cleaner to make `AskPerformFreeAction` behave the same way for both human and AI players when `isForced: true` is set.

**Comment by Sandrem** [comment]
I like your decision how to fix this - I merge it.

Maybe we need to check priorities of add common actions and set for them priority 0 only if AI never uses them (like current Boost/BR - just no AI present for these actions), but in other cases set priority as 1 - so they will be taken only is there are no actions with higher priority.

**Comment by bitsai** [comment]
@Sandrem that's an interesting idea!  I'll keep it in mind next time there's an actions-related issue.

**Pull request merged**
