### PR TITLE
Allow auto screen rotation between the 2 landscape options

### PR DESCRIPTION
**Pull request by savagerose**
On mobile, this allows screen rotation between the 2 landscape options. I think this is pretty typical for fullscreen apps, since folks might need to rotate their phone / tablet.

### CODE REVIEW

**Comment by Sandrem** [comment]
Rework of combat UI is planned. I will test auto screen rotation with updated UI later.
(I have some doubts - auto rotation can be annoying, maybe we need separate option for this)

**Comment by savagerose** [comment]
Cool — I think the OS-level rotation lock is  the best solution if it gets annoying, unless we have a specific reason to break that convention. 

(This pull request refers to the whole screen’s rotation in case you’re thinking camera rotation. Though I actually have some in-progress improved touch screen camera controls too, to add zoom and pan, so I’d be curious if you’re working on anything related to that as well. :) )

**Comment by rune-b** [comment]
I agree on making it an option. It is annoying to have to turn off rotation for all apps just because you have one where you don't want auto-rotate. I don't think I ever would want to play Fly Casual in portrait mode on my phone. Maybe it will be more useful on tablets

**Comment by savagerose** [comment]
I agree about portrait mode probably not being useful, my suggestion is to allow auto rotation between the two landscape orientations. 

For my use cases I don’t get much accidental rotation (when portrait is disabled) so an app specific switch isn’t very important, but I suspect we just have slightly different experiences there. :)

I’d argue even if we want an option, it would be good to enable rotation before we implement that, because otherwise it’s impossible to use the app with a tablet stand that holds the screen in the wrong landscape orientation.

**Pull request closed without merging**
