### PR TITLE
Update MainMenu.unity

### PR DESCRIPTION
**Pull request by DejaFu**
Increased scroll speed to 50 from 10 in BrowseSavedSquadsPanel.

### CODE REVIEW

**Comment by DejaFu** [comment]
Hopefully this one meets all the criteria.  If so, I'll start on the others.

**Comment by Sandrem** [comment]
Seems to be OK, you can continue with another pull requests.

**Comment by DejaFu** [comment]
I pushed my development from this one, and it keeps reverting the MainMenu.unity change back to what it was originally (i.e. the Slider Sensitivity is 10 instead of 50 like this change was supposed to do).  Can you please check to see if the slider sensitivity is 50 for you in BrowseSavedSquadsPanel?

**Comment by DejaFu** [comment]
If it is, then my development saying it is "one commit ahead" of your development means mine has a commit that is reverting this change. >:(

**Comment by DejaFu** [comment]
Never mind.  I figured it out.  My development is right, but for some reason my "new" target lock branch is missing the merge.

**Pull request merged**
