### PR TITLE
fix #583

### LINKED ISSUE #583: moldy crow multiple focus tokens in combat NULL exception
I found a bug. I was able to narrow it down to it being some issue with the "Moldy Crow" title on the HWK. 

**Description**
If the HWK with the moldy crow title goes into combat with multiple focus tokens. The game gets confused and crashes. I don't think the game logic knows how to handle having multiple focus tokens when it tryies to create the multiple option choices for the dice modification sub phase of of combat for the moldy crow.

I say this because I also tried with 1 focus token, and no bug occurred. NULL reference only happens if the moldy crow goes into combat with 2 or more focus tokens. 

**Reproduce:**
It took me some time to figure out, but once I narrowed it down, this bug is fairly easy to reproduce. Reproducible on all pilots for hwk while moldy crow is attached. Rebel and Scum.

### PR DESCRIPTION
**Pull request by NickyDaB**
fixes bug #583 

- fix by checking how many focus tokens. and only add them to option list if it is the first occurrence. 
- went in and also did a check for evade tokens as well. 
- by fixing here, will address other instances of problem; not limit it to only moldy crow instance. 
- also added two new functions: GetModifyCombatDiceTokens() and  GetAllUniqueTokens()

### CODE REVIEW

**Comment by Sandrem** [comment]
I have doubts about this way to fix bug.

1) GetAllUniqueTokens - are two blue target lock tokens with different letter unique?
2) GetAllUniqueTokens : GetToken(searchToken.GetType(), ' ') will not return any Target Lock token - char must be * if you want to select target lock token with any letter.
3) Is there any places where we can use GetModifyCombatDiceTokens method?
4) ShowDiceModificationButtons() seems too big, with special cases for two types of tokens...

I think that I have more elegant way to fix this bug.
I don't close this pull request for now. I will create my own version of this fix to compare ideas.

**Comment by NickyDaB** [comment]
Those two functions are starter functions for how I think we can fix the issue in the future. But the actual fix for the NULL exception is in "Assets/Scripts/View/Combat/Combat.cs" 

here I set a boolean to true the first time we add a focus or evade modification to the dialogue box. then when we want to add another focus or evade modification I check against the boolean. 

it stops the game from crashing, but in the future we can swap that out to use the two function I started to stub out. I don't actually use those functions yet. but I think they could be a good start to solving the problem in the future.

**Comment by NickyDaB** [comment]
you should at least pull in "Assets/Scripts/View/Combat/Combat.cs" that will stop the game from crashing.

**Comment by Sandrem** [comment]
My idea how to fix this bug:
https://github.com/Sandrem/FlyCasual/pull/586/files

As you can use only one Focus token effect per attack/defence, when list of all available dice modifications is generated, I check if this dice modification effect is already present in list. And if it is present - I don't add duplicates.

**Comment by NickyDaB** [comment]
sounds good!

**Comment by Sandrem** [comment]
So I close your version of fix and accept my version instead.

Just one advice - try to find roots of problem, this helps to keep code simple.

**Pull request closed without merging**
