### PR TITLE
Load screen improved scrolling

### PR DESCRIPTION
**Pull request by DejaFu**
Increased the scroll speed of the two different load screens to 50, so that scrolling through them with the mouse wheel is much more responsive.

### CODE REVIEW

**Comment by Sandrem** [comment]
See list of changed files, too many of them are not needed.
Many of changes revert things that were added in 0.8.1

**Comment by Sandrem** [comment]
Same problem with all another pull request.
Please:
1) Update your branch to current state of development branch.
2) Modify/replace files that have required changes.
3) Check what do you change (for example, I use GitHub Desktop app for this)
4) Only then commit and create pull request, check "Files changed" tab.

Pull request must have only required changes. Otherwise I will not accept it.

**Comment by Sandrem** [comment]
Also I recommend you to create only one pull request in this way first (the smallest change what you have), I will check it and if it is OK - I will accept it. And only then to do the same with all your another changes.

**Comment by DejaFu** [comment]
Bleh.  I tried to do exactly this BEFORE uploading these pulls.  I reset my development right after I got back from work, and pulled from the source.  Then I made one set of changes and created the pull request.  Then I set it back and did the same for each of the others.  Apparently I failed to reset development properly?  And since that is key to the whole thing, I have to do all the work over again a third time. >:(  GitHub really needs a "only include this file" in their pull requests, or a way to remove erroneous files from the pull requests.

**Pull request closed without merging**
