### PR TITLE
Advanced Proton Torpedoes

### PR DESCRIPTION
**Pull request by bwakefield27**

### CODE REVIEW

**Comment by Sandrem** [comment]
GetActionEffectPriority must be changed to allow AI understand order of dice modifications.

Logic must be: if current sombat step is attack and blanks > 0 then priority is 100 (highest, before AI tries to reroll blanks)

**Comment by Sandrem** [comment]
See GenericAction.GetActionEffectPriority to understand AI priorities

**Comment by bwakefield27** [comment]
Yup; you are right. Should be good now.

**Comment by Sandrem** [comment]
Everything is OK now

**Pull request merged**
