### PR TITLE
Battle meditation

### PR DESCRIPTION
**Pull request by belk**
copy of pull #1661 but on its own branch

### CODE REVIEW

**Comment by Sandrem** [comment]
I remember that I saw some conversation about work of this upgrade in Slack. Is this card ready to be merged, or still some work is required?

**Comment by belk** [comment]
This card works at the moment, but each battle meditation coordinate counts as it's own action.  I spent some time today trying to rework the coordinate action to allow multiple targets, but it gets complicated really fast.  I would suggest merging this for now, and reworking it when the CoordinateAction is ready to accept multiple targets.  Other cards would benefit from that as well (General Hux for example)

**Comment by Sandrem** [comment]
I decided to release this card in later version. I will try to rework the coordinate action in 0.8.1

**Comment by bitsai** [comment]
The new costs for Battle Meditation for each initiative value are now available:

IN 0: 0
IN 1: 2
IN 2: 4
IN 3: 6
IN 4: 8
IN 5: 10
IN 6: 12

(source: https://images-cdn.fantasyflightgames.com/filer_public/90/05/900509d3-011b-4c37-a484-a39ed0e112bc/onlinepoints_republic_july_2019.pdf)

**Comment by Sandrem** [comment]
I added support of multi-target selection during implementation of General Hux card. So, I decided to use the same way to implement Battle Meditation, as similar ability.
Also, I changed how "cannot coordinate limited ships" work to handle possible situation when ship with white coordinate action can install this upgrade.
I used UpgradeInfo and cost that were provided by you, but code of ability was completely changed, you can see current version here: https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Content/SecondEdition/Upgrades/Force/BattleMeditation.cs

Thank you for help anyway, otherwise I would left implementation of this upgrade for later update.

I close this pull request without merging, Battle Meditation is added by another pull request.

**Pull request closed without merging**
